if (!require("plyr")) install.packages("plyr",repos = "https://cloud.r-project.org")
if (!require("dplyr")) install.packages("dplyr",repos = "https://cloud.r-project.org")
if (!require("optparse")) install.packages("optparse",repos = "https://cloud.r-project.org")
if (!require("rjson")) install.packages("rjson",repos = "https://cloud.r-project.org")
if (!require("gmp")) install.packages("gmp",repos = "https://cloud.r-project.org")
if (!require("vctrs")) install.packages("vctrs",repos = "https://cloud.r-project.org")
if (!require("tidyr")) install.packages("tidyr",repos = "https://cloud.r-project.org")
if (!require("ggplot2")) install.packages("ggplot2",repos = "https://cloud.r-project.org")
if (!require("colorspace")) install.packages("colorspace",repos = "https://cloud.r-project.org")
if (!require("stringr")) install.packages("stringr",repos = "https://cloud.r-project.org")
if (!require("latex2exp")) install.packages("latex2exp",repos = "https://cloud.r-project.org")
if (!require("igraph")) install.packages("igraph",repos = "https://cloud.r-project.org")
if (!require("ggraph")) install.packages("ggraph",repos = "https://cloud.r-project.org")
if (!require("scales")) install.packages("scales",repos = "https://cloud.r-project.org")
if (!require("matrixStats")) install.packages("matrixStats",repos = "https://cloud.r-project.org")
if (!require("patchwork")) install.packages("patchwork",repos = "https://cloud.r-project.org")
if (!require("colorspace")) install.packages("colorspace")
